compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

preferInteractive: true

preferReuse: true

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
